server:
  port: 8080

spring:
  application:
    name: pod-team-management

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public

  flyway:
    enabled: false
    locations: classpath:db/migration
    clean-disabled: true
    validate-on-migrate: false

  jackson:
    serialization:
      write-dates-as-timestamps: false

  data:
    redis:
      timeout: 3000ms

  datasource:
    url: jdbc:postgresql://localhost:5432/pod
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 1800000
      connection-timeout: 30000

logging:
  level:
    com.pod: INFO